# 基础镜像
FROM redis
# author
MAINTAINER westChina

# 挂载目录
VOLUME /home/westChina/redis
# 创建目录
RUN mkdir -p /home/westChina/redis
# 指定路径
WORKDIR /home/westChina/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/westChina/redis/redis.conf
