# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER westChina

# 挂载目录
VOLUME /home/westChina
# 创建目录
RUN mkdir -p /home/westChina
# 指定路径
WORKDIR /home/westChina
# 复制jar文件到路径
COPY ./jar/westChina-visual-monitor.jar /home/westChina/westChina-visual-monitor.jar
# 启动系统服务
ENTRYPOINT ["java","-jar","westChina-visual-monitor.jar"]