# 基础镜像
FROM nginx
# author
MAINTAINER westChina

# 挂载目录
VOLUME /home/westChina/projects/westChina-ui
# 创建目录
RUN mkdir -p /home/westChina/projects/westChina-ui
# 指定路径
WORKDIR /home/westChina/projects/westChina-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/main /home/westChina/projects/westChina-ui/main
COPY ./html/administrator /home/westChina/projects/westChina-ui/administrator
