const getters = {
  sidebar: state => state.app.sidebar,
  size: state => state.app.size,
  device: state => state.app.device,

  visitedViews: state => state.tagsView.visitedViews,
  cachedViews: state => state.tagsView.cachedViews,

  token: state => state.user.token,
  avatar: state => state.user.avatar,
  enterpriseName: state => state.user.enterpriseName,
  enterpriseSystemName: state => state.user.enterpriseSystemName,
  isLessor: state => state.user.isLessor,
  logo: state => state.user.logo,
  name: state => state.user.name,
  introduction: state => state.user.introduction,
  roles: state => state.user.roles,
  permissions: state => state.user.permissions,
  bucketName: state => state.user.bucketName,

  permission_routes: state => state.permission.routes,
  topbarRouters: state => state.permission.topbarRouters,
  defaultRoutes: state => state.permission.defaultRoutes,
  sidebarRouters: state => state.permission.sidebarRouters,

  invert: state => state.ctTools.invert,
  hflip: state => state.ctTools.hflip,
  vflip: state => state.ctTools.vflip,
  pixelReplication: state => state.ctTools.pixelReplication,
  rotation: state => state.ctTools.rotation,

  isShowPatientInfo: state => state.ctTools.isShowPatientInfo,
  isShowStudyInfo: state => state.ctTools.isShowStudyInfo,
  isShowSeriesInfo: state => state.ctTools.isShowSeriesInfo,
  isShowInstancesInfo: state => state.ctTools.isShowInstancesInfo,
  isShowImageInfo: state => state.ctTools.isShowImageInfo,
  isShowEquipmentInfo: state => state.ctTools.isShowEquipmentInfo,
  isShowUIDS: state => state.ctTools.isShowUIDS,

  openStudy: state => state.ctTools.openStudy,
  lesionDetectTick: state => state.ctTools.lesionDetectTick,
  lesionDetectLoading: state => state.ctTools.lesionDetectLoading,
  lesionDetectPayload: state => state.ctTools.lesionDetectPayload,
  lesionSeriesDialogVisible: state => state.ctTools.lesionSeriesDialogVisible,
  lesionResultsByDicomId: state => state.ctTools.lesionResultsByDicomId,
  lesionDetectLogs: state => state.ctTools.lesionDetectLogs,
  lesionDetectProgress: state => state.ctTools.lesionDetectProgress,
  lesionDetectStage: state => state.ctTools.lesionDetectStage,
  lesionDetectStats: state => state.ctTools.lesionDetectStats,
  lesionLogPanelVisible: state => state.ctTools.lesionLogPanelVisible,
  activeLesionTaskId: state => state.ctTools.activeLesionTaskId,
  activeLesionTaskDicomId: state => state.ctTools.activeLesionTaskDicomId,
  lesionShowLogsTick: state => state.ctTools.lesionShowLogsTick,
  lesionCancelTick: state => state.ctTools.lesionCancelTick,
  lesionDetectEngine: state => state.ctTools.lesionDetectEngine,
  lesionDetectSubEngine: state => state.ctTools.lesionDetectSubEngine,
  lesionEngineCatalog: state => state.ctTools.lesionEngineCatalog,
  activeViewerSeriesDicomId: state => state.ctTools.activeViewerSeriesDicomId,

  patCardId: state => state.ctPatientInfo.patCardId,
  patName: state => state.ctPatientInfo.patName,
  patPhone: state => state.ctPatientInfo.patPhone,
  studySeriesList: state => state.ctPatientInfo.studySeriesList,

  dicomOfPatCardId: state => state.dicom.dicomOfPatCardId,

  makerOfPatCardId: state => state.makerImage.makerOfPatCardId,
  makerImageList: state => state.makerImage.makerImageList,
  makerImageInitInfo: state => state.makerImage.makerImageInitInfo,

  aiLesionOfPatCardId: state => state.aiLesion.aiLesionOfPatCardId,
  pendingAiLesionId: state => state.aiLesion.pendingAiLesionId,

  makerNeed: state => state.makerToolsOfMe.makerNeed,
}
export default getters
